### ISSUE TITLE
Crash on some devices 

### ISSUE THREAD

**Issue by arnaudruffin** [Orange-OpenSource/m-dan#4]
Getting a NPE when going to "Alternative textuelle" -> "l'état des éléments"
on Motorola nexus 6 and on my emulator (not on a galaxy s6)

Here is the stack
`FATAL EXCEPTION: main
                                                                   Process: com.orange.ease.dan, PID: 6171
                                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.drawable.Drawable.setState(int[])' on a null object reference
                                                                       at android.widget.TabWidget.dispatchDraw(TabWidget.java:375)
                                                                       at android.view.View.draw(View.java:17073)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16052)
                                                                       at android.view.View.draw(View.java:16836)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16047)
                                                                       at android.view.View.draw(View.java:16836)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16047)
                                                                       at android.view.View.draw(View.java:16836)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16047)
                                                                       at android.view.View.draw(View.java:16836)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16047)
                                                                       at android.view.View.draw(View.java:16836)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16047)
                                                                       at android.view.View.draw(View.java:16836)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                       at android.view.View.draw(View.java:17073)
                                                                       at android.widget.ScrollView.draw(ScrollView.java:1722)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16052)
                                                                       at android.view.View.draw(View.java:16836)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16047)
                                                                       at android.view.View.draw(View.java:16836)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16047)
                                                                       at android.view.View.draw(View.java:16836)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16047)
                                                                       at android.view.View.draw(View.java:16836)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16047)
                                                                       at android.view.View.draw(View.java:16836)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16047)
                                                                       at android.view.View.draw(View.java:16836)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16047)
                                                                       at android.view.View.draw(View.java:16836)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                       at android.view.View.draw(View.java:17073)
                                                                       at com.android.internal.policy.DecorView.draw(DecorView.java:751)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16052)
                                                                       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:656)
                                                                       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:662)
                                                                       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:770)
                                                                       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2796)
                                                                       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2604)
                                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2211)`

**Comment by arnaudruffin** [comment]
Apparently, crashes on every device with android >= 7.0

see ExStateElmts1Fragment and its TabHost element for related code
